2024-12-17 20:07:50,771 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 20:07:50,774 - root - INFO - Searching for GoPro cameras...
2024-12-17 20:07:50,913 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 20:07:50,914 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 20:07:55,780 - root - INFO - Found the following GoPro devices:
2024-12-17 20:07:55,781 - root - INFO - Name: C3461350386740._gopro-web._tcp.local., IP: 172.27.140.51
2024-12-17 20:07:55,869 - root - INFO - Name: C3461326143885._gopro-web._tcp.local., IP: 172.28.185.51
2024-12-17 20:07:55,881 - root - INFO - Cache updated successfully with newly discovered devices.
2024-12-17 20:07:55,882 - root - INFO - Resetting and enabling USB control on all cameras...
2024-12-17 20:07:55,883 - root - INFO - Resetting USB control on camera 172.27.140.51.
2024-12-17 20:07:55,885 - root - INFO - Resetting USB control on camera 172.28.185.51.
2024-12-17 20:07:55,910 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 20:07:55,914 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 20:07:55,966 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 200 3
2024-12-17 20:07:55,966 - root - INFO - USB control disabled on camera 172.28.185.51.
2024-12-17 20:07:55,981 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 200 3
2024-12-17 20:07:55,982 - root - INFO - USB control disabled on camera 172.27.140.51.
2024-12-17 20:07:57,978 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 20:07:57,983 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 20:07:58,035 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 20:07:58,035 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 20:07:58,036 - root - INFO - USB control enabled on camera 172.27.140.51.
2024-12-17 20:07:58,037 - root - INFO - USB control enabled on camera 172.28.185.51.
2024-12-17 20:07:58,038 - root - INFO - Synchronizing time on all cameras...
2024-12-17 20:07:58,042 - root - ERROR - Failed to sync time: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
2024-12-17 20:07:58,042 - root - ERROR - An error occurred: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
